### ISSUE TITLE
Unable to deploy additional fields

### ISSUE THREAD

**Issue by blackbasket** [derhansen/sf_event_mgt_extend_demo#14]
Hi,

I have extended your extension about a year ago. Now, I need two more fields. I edited the files and uploaded the changes.

But for some reason the fields are not created. Do I have to do more than that? I cannot find issues in my files.

Regards,
Marcel

**Comment by derhansen** [comment]
If you are using TYPO3 v10, then you must do some adaptions to your own extension, since some things changed in the TYPO3 core. Please refer to my [blogpost](https://www.derhansen.de/2019/03/extending-extbase-domain-models-and.html) about the topic and make sure you follow all steps provided in the README.md in this extension

**Comment by blackbasket** [comment]
Thanks for the quick reply Torben... I am using v10, but even last year for initial deployment ;) I will check it and come back to you...

**Comment by blackbasket** [comment]
I found the issue...  a bracket was misplaced... I had not seen this on Friday^^

**Comment by derhansen** [comment]
👍  nice it is working now
